wall_follower_controller_cpp:
  ros__parameters:
    use_sim_time: true
    
    # Control parameters - SAFE DISTANCES
    desired_distance: 0.8        # Keep 80cm from wall (safe distance)
    forward_speed: 0.12          # Slower for safety
    search_speed: 0.08           # Slow search
    max_angular_speed: 0.5       # Controlled rotation
    
    # PID parameters
    kp: 2.5                      # Proportional gain
    ki: 0.0                      # No integral
    kd: 0.3                      # Small derivative
    
    # Safety distances - INCREASED FOR NO COLLISION
    emergency_stop: 0.4         # Stop at 40cm from obstacles
    slow_down_dist: 0.6         # Start slowing at 60cm
    wall_min: 0.5              # Never closer than 40cm to wall
    wall_lost: 1.5              # Lose wall at 1.5m
    side_clearance: 0.5         # 50cm side clearance
    
    # Wall detection parameters
    wall_range: 1.5             # Max wall detection range
    consistency: 0.3            # Consistency threshold
    
    # Timing parameters
    control_frequency: 20.0      # Control loop frequency (Hz)
    laser_timeout: 1.0          # Timeout for laser data (s)
    
    # Debug parameters
    debug_mode: false           # Enable debug output
    verbose_logging: false      # Enable verbose logging