wall_follower_controller_cpp:
  ros__parameters:
    use_sim_time: true
    
    # Control parameters - OPTIMIZED FOR FULL MAP EXPLORATION
    desired_distance: 0.8        # Stay far from wall
    forward_speed: 0.25          # Faster for better exploration
    search_speed: 0.20           # Faster search speed
    max_angular_speed: 0.8       # Can turn faster when needed
    
    # PID parameters - MORE RESPONSIVE
    kp: 2.0                      # Increased proportional gain
    ki: 0.0                      # Integral not used
    kd: 0.5                      # Moderate derivative gain
    
    # Safety distances - LARGE SPACING FOR OBSTACLES
    emergency_stop: 0.55         # Stop if obstacle within this distance
    slow_down_dist: 0.85         # Start slowing down distance
    wall_min: 0.50              # Minimum distance to wall (don't get closer)
    wall_lost: 2.5              # Max distance before losing wall
    side_clearance: 0.45        # Side obstacle clearance
    
    # Wall detection parameters
    wall_range: 2.5             # Maximum range for wall detection (m)
    consistency: 0.4            # Allowed variation in wall measurements (m)
    
    # Timing parameters
    control_frequency: 20.0      # Control loop frequency (Hz)
    laser_timeout: 1.0          # Timeout for laser data (s)
    
    # Debug parameters
    debug_mode: false           # Enable debug output
    verbose_logging: false      # Enable verbose logging